package OnAppManagement::Model::LocalStorage;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'OnAppManagement::SchemaClass',
    
    connect_info => {
        dsn => 'dbi:SQLite:db/onapp.sqlite3',
        user => '',
        password => '',
    }
);

=head1 NAME

OnAppManagement::Model::LocalStorage - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<OnAppManagement>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<OnAppManagement::SchemaClass>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Brian Kelly

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
